# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multidb_router_app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseuser',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
